//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store_of__goods
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GoodsEntities : DbContext
    {
        public GoodsEntities()
            : base("name=GoodsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WAR_FAS_IMAGE> WAR_FAS_IMAGE { get; set; }
        public virtual DbSet<WAREHOUSE_DATA> WAREHOUSE_DATA { get; set; }
        public virtual DbSet<WAREHOUSE_MAIN> WAREHOUSE_MAIN { get; set; }
    }
}
