//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store_of__goods
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAR_FAS_IMAGE
    {
        public long ID { get; set; }
        public decimal FAS { get; set; }
        public byte[] IMAGE_1 { get; set; }
        public byte[] IMAGE_2 { get; set; }
        public byte[] IMAGE_3 { get; set; }
        public byte[] IMAGE_4 { get; set; }
        public byte[] IMAGE_5 { get; set; }
        public string NOTE { get; set; }
    }
}
