//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store_of__goods
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAREHOUSE_MAIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WAREHOUSE_MAIN()
        {
            this.WAREHOUSE_DATA = new HashSet<WAREHOUSE_DATA>();
        }
    
        public long ID { get; set; }
        public System.DateTime CREATION_DATE { get; set; }
        public System.DateTime CALCULATION_DATE { get; set; }
        public string NAME { get; set; }
        public string NOTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WAREHOUSE_DATA> WAREHOUSE_DATA { get; set; }
    }
}
