//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store_of__goods
{
    using System;
    using System.Collections.Generic;
    
    public partial class WAREHOUSE_DATA
    {
        public long ID { get; set; }
        public long WAREHOUSE_MAIN_ID { get; set; }
        public Nullable<decimal> KOD_IZD { get; set; }
        public Nullable<decimal> KOL { get; set; }
        public string NCW { get; set; }
        public Nullable<decimal> RST { get; set; }
        public Nullable<decimal> RZM { get; set; }
        public string RZM_PRINT { get; set; }
        public Nullable<decimal> SRT { get; set; }
        public string NOT1 { get; set; }
        public Nullable<decimal> MASSA { get; set; }
        public Nullable<decimal> CNP { get; set; }
        public Nullable<decimal> CNO { get; set; }
        public Nullable<decimal> CNR { get; set; }
        public Nullable<decimal> CNV { get; set; }
        public Nullable<decimal> NDS { get; set; }
        public string EAN { get; set; }
        public Nullable<decimal> KOD { get; set; }
        public Nullable<decimal> SAR { get; set; }
        public string NAR { get; set; }
        public string NGPR { get; set; }
        public string BREND { get; set; }
        public string KOMPLEKT { get; set; }
        public Nullable<decimal> FAS { get; set; }
    
        public virtual WAREHOUSE_MAIN WAREHOUSE_MAIN { get; set; }
    }
}
